# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hud.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setGeometry(0, 0, 1920, 1080)
        MainWindow.setStyleSheet("background-color: transparent;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.yourtotal = QtWidgets.QLabel(self.centralwidget)
        self.yourtotal.setGeometry(QtCore.QRect(360, 40, 161, 31))
        self.yourtotal.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(125, 182, 255);\n"
"background-color: rgb(58, 58, 58);")
        self.yourtotal.setAlignment(QtCore.Qt.AlignCenter)
        self.yourtotal.setObjectName("yourtotal")
        self.theirtotal = QtWidgets.QLabel(self.centralwidget)
        self.theirtotal.setGeometry(QtCore.QRect(360, 150, 161, 31))
        self.theirtotal.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 120, 150);\n"
"background-color: rgb(58, 58, 58);")
        self.theirtotal.setAlignment(QtCore.Qt.AlignCenter)
        self.theirtotal.setObjectName("theirtotal")
        self.profit = QtWidgets.QLabel(self.centralwidget)
        self.profit.setGeometry(QtCore.QRect(360, 80, 161, 31))
        self.profit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(125, 182, 255);\n"
"background-color: rgb(58, 58, 58);")
        self.profit.setAlignment(QtCore.Qt.AlignCenter)
        self.profit.setObjectName("profit")
        self.iteminfo = QtWidgets.QLabel(self.centralwidget)
        self.iteminfo.setGeometry(QtCore.QRect(600, 420, 300, 150))
        self.iteminfo.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(125, 182, 255);\n"
"background-color: rgb(58, 58, 58);")
        self.iteminfo.setAlignment(QtCore.Qt.AlignCenter)
        self.iteminfo.setObjectName("iteminfo")
        self.iteminfo.setWordWrap(True)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 40, 281, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.youritems = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.youritems.setContentsMargins(0, 0, 0, 0)
        self.youritems.setSpacing(0)
        self.youritems.setObjectName("youritems")
        self.youritem2 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.youritem2.setStyleSheet("background: transparent;\n"
"border: 2px solid white;\n"
"border-color: rgb(125, 182, 255);")
        self.youritem2.setObjectName("youritem2")
        self.yourvalue2 = QtWidgets.QLabel(self.youritem2)
        self.yourvalue2.setGeometry(QtCore.QRect(0, 0, 41, 21))
        self.yourvalue2.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(125, 182, 255);\n"
"background-color: rgb(58, 58, 58);")
        self.yourvalue2.setAlignment(QtCore.Qt.AlignCenter)
        self.yourvalue2.setObjectName("yourvalue2")
        self.youritems.addWidget(self.youritem2)
        self.youritem3 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.youritem3.setStyleSheet("background: transparent;\n"
"border: 2px solid white;\n"
"border-color: rgb(125, 182, 255);")
        self.youritem3.setObjectName("youritem3")
        self.yourvalue3 = QtWidgets.QLabel(self.youritem3)
        self.yourvalue3.setGeometry(QtCore.QRect(0, 0, 41, 21))
        self.yourvalue3.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(125, 182, 255);\n"
"background-color: rgb(58, 58, 58);")
        self.yourvalue3.setAlignment(QtCore.Qt.AlignCenter)
        self.yourvalue3.setObjectName("yourvalue3")
        self.youritems.addWidget(self.youritem3)
        self.youritem4 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.youritem4.setStyleSheet("background: transparent;\n"
"border: 2px solid white;\n"
"border-color: rgb(125, 182, 255);")
        self.youritem4.setObjectName("youritem4")
        self.yourvalue4 = QtWidgets.QLabel(self.youritem4)
        self.yourvalue4.setGeometry(QtCore.QRect(0, 0, 41, 21))
        self.yourvalue4.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(125, 182, 255);\n"
"background-color: rgb(58, 58, 58);")
        self.yourvalue4.setAlignment(QtCore.Qt.AlignCenter)
        self.yourvalue4.setObjectName("yourvalue4")
        self.youritems.addWidget(self.youritem4)
        self.youritem1 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.youritem1.setStyleSheet("background: transparent;\n"
"border: 2px solid white;\n"
"border-color: rgb(125, 182, 255);")
        self.youritem1.setObjectName("youritem1")
        self.yourvalue1 = QtWidgets.QLabel(self.youritem1)
        self.yourvalue1.setGeometry(QtCore.QRect(0, 0, 41, 21))
        self.yourvalue1.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(125, 182, 255);\n"
"background-color: rgb(58, 58, 58);")
        self.yourvalue1.setAlignment(QtCore.Qt.AlignCenter)
        self.yourvalue1.setObjectName("yourvalue1")
        self.youritems.addWidget(self.youritem1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(70, 150, 281, 91))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.theiritems = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.theiritems.setContentsMargins(0, 0, 0, 0)
        self.theiritems.setSpacing(0)
        self.theiritems.setObjectName("theiritems")
        self.theiritem1 = QtWidgets.QWidget(self.horizontalLayoutWidget_2)
        self.theiritem1.setStyleSheet("background: transparent;\n"
"border: 2px solid white;\n"
"border-color: rgb(255, 120, 150);")
        self.theiritem1.setObjectName("theiritem1")
        self.theirvalue1 = QtWidgets.QLabel(self.theiritem1)
        self.theirvalue1.setGeometry(QtCore.QRect(0, 0, 41, 21))
        self.theirvalue1.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 120, 150);\n"
"background-color: rgb(58, 58, 58);")
        self.theirvalue1.setAlignment(QtCore.Qt.AlignCenter)
        self.theirvalue1.setObjectName("theirvalue1")
        self.theiritems.addWidget(self.theiritem1)
        self.theiritem2 = QtWidgets.QWidget(self.horizontalLayoutWidget_2)
        self.theiritem2.setStyleSheet("background: transparent;\n"
"border: 2px solid white;\n"
"border-color: rgb(255, 120, 150);")
        self.theiritem2.setObjectName("theiritem2")
        self.theirvalue2 = QtWidgets.QLabel(self.theiritem2)
        self.theirvalue2.setGeometry(QtCore.QRect(0, 0, 41, 21))
        self.theirvalue2.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 120, 150);\n"
"background-color: rgb(58, 58, 58);")
        self.theirvalue2.setAlignment(QtCore.Qt.AlignCenter)
        self.theirvalue2.setObjectName("theirvalue2")
        self.theiritems.addWidget(self.theiritem2)
        self.theiritem3 = QtWidgets.QWidget(self.horizontalLayoutWidget_2)
        self.theiritem3.setStyleSheet("background: transparent;\n"
"border: 2px solid white;\n"
"border-color: rgb(255, 120, 150);")
        self.theiritem3.setObjectName("theiritem3")
        self.theirvalue3 = QtWidgets.QLabel(self.theiritem3)
        self.theirvalue3.setGeometry(QtCore.QRect(0, 0, 41, 21))
        self.theirvalue3.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 120, 150);\n"
"background-color: rgb(58, 58, 58);")
        self.theirvalue3.setAlignment(QtCore.Qt.AlignCenter)
        self.theirvalue3.setObjectName("theirvalue3")
        self.theiritems.addWidget(self.theiritem3)
        self.theiritem4 = QtWidgets.QWidget(self.horizontalLayoutWidget_2)
        self.theiritem4.setStyleSheet("background: transparent;\n"
"border: 2px solid white;\n"
"border-color: rgb(255, 120, 150);")
        self.theiritem4.setObjectName("theiritem4")
        self.theirvalue4 = QtWidgets.QLabel(self.theiritem4)
        self.theirvalue4.setGeometry(QtCore.QRect(0, 0, 41, 21))
        self.theirvalue4.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 120, 150);\n"
"background-color: rgb(58, 58, 58);")
        self.theirvalue4.setAlignment(QtCore.Qt.AlignCenter)
        self.theirvalue4.setObjectName("theirvalue4")
        self.theiritems.addWidget(self.theiritem4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.yourtotal.setText(_translate("MainWindow", "Your total: 0 values"))
        self.theirtotal.setText(_translate("MainWindow", "Their total: 0 values"))
        self.profit.setText(_translate("MainWindow", "Profit: 0 values"))
        self.iteminfo.setText(_translate("MainWindow", "The info will display here as you hover on an item!"))
        self.yourvalue2.setText(_translate("MainWindow", "0"))
        self.yourvalue3.setText(_translate("MainWindow", "0"))
        self.yourvalue4.setText(_translate("MainWindow", "0"))
        self.yourvalue1.setText(_translate("MainWindow", "0"))
        self.theirvalue1.setText(_translate("MainWindow", "0"))
        self.theirvalue2.setText(_translate("MainWindow", "0"))
        self.theirvalue3.setText(_translate("MainWindow", "0"))
        self.theirvalue4.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
