# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\user\PycharmProjects\supreme\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(200, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(200, 200))
        self.centralwidget.setMaximumSize(QtCore.QSize(200, 200))
        self.centralwidget.setObjectName("centralwidget")
        self.update = QtWidgets.QPushButton(self.centralwidget)
        self.update.setGeometry(QtCore.QRect(10, 130, 181, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update.sizePolicy().hasHeightForWidth())
        self.update.setSizePolicy(sizePolicy)
        self.update.setObjectName("update")
        self.lastupdate = QtWidgets.QLabel(self.centralwidget)
        self.lastupdate.setGeometry(QtCore.QRect(10, 170, 181, 21))
        self.lastupdate.setTextFormat(QtCore.Qt.AutoText)
        self.lastupdate.setAlignment(QtCore.Qt.AlignCenter)
        self.lastupdate.setObjectName("lastupdate")
        self.editmode = QtWidgets.QPushButton(self.centralwidget)
        self.editmode.setGeometry(QtCore.QRect(10, 90, 181, 41))
        self.editmode.setObjectName("editmode")
        self.hudopacity = QtWidgets.QSlider(self.centralwidget)
        self.hudopacity.setGeometry(QtCore.QRect(10, 20, 181, 22))
        self.hudopacity.setMaximum(100)
        self.hudopacity.setProperty("value", 100)
        self.hudopacity.setOrientation(QtCore.Qt.Horizontal)
        self.hudopacity.setInvertedAppearance(False)
        self.hudopacity.setInvertedControls(False)
        self.hudopacity.setObjectName("hudopacity")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 181, 20))
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.hudscale = QtWidgets.QSlider(self.centralwidget)
        self.hudscale.setGeometry(QtCore.QRect(10, 50, 181, 22))
        self.hudscale.setMinimum(50)
        self.hudscale.setMaximum(200)
        self.hudscale.setProperty("value", 100)
        self.hudscale.setOrientation(QtCore.Qt.Horizontal)
        self.hudscale.setInvertedAppearance(False)
        self.hudscale.setInvertedControls(False)
        self.hudscale.setObjectName("hudscale")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 181, 20))
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.label_2.raise_()
        self.update.raise_()
        self.lastupdate.raise_()
        self.editmode.raise_()
        self.hudopacity.raise_()
        self.hudscale.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.update.setText(_translate("MainWindow", "Update values"))
        self.lastupdate.setText(_translate("MainWindow", "Last update: n/a minutes ago"))
        self.editmode.setText(_translate("MainWindow", "Enter edit mode"))
        self.label_2.setText(_translate("MainWindow", "HUD opacity"))
        self.label_3.setText(_translate("MainWindow", "HUD scale"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
